### ISSUE TITLE
Galaxy Watch Wear OS support?

### ISSUE THREAD

**Issue by PorreKaj** [mkaflowski/ShelfTime#1]
Shelftime is sadly not compatible with my Galaxy Watch 4, any chance theres an easy fix for supporting Samsungs Wear OS, or is my Watch4 perchance to old to be listed as compatible?

**Comment by mkaflowski** [comment]
What system version do you have?

**Comment by PorreKaj** [comment]
Galaxy Watch 4
Wear OS 4.0

Not sure if these are the numbers you are looking for.


Sendt fra Outlook til Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mkaflowski** [comment]
It should work on WearOS 2 and above. Do you get error while installing it or something crash after that?

**Comment by PorreKaj** [comment]
No not at all, the play store wont let me install it as I dont have any "compatible devices"

Sendt fra Outlook til Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mkaflowski** [comment]
That's strange. Did you try to find the app in Play Store on the watch? You can try to install apk directly.

**Comment by PorreKaj** [comment]
Installing from Play store on the watch works.
Installing from the playstore on the phone, after selecting the watch does not.

Strange issue indeed. but at least now I'm closer to a functioning solution. thanks

**Comment by mkaflowski** [comment]
Great! On the website make sure that you don't have any parameters in the link (something after "&" at the end).
