### ISSUE TITLE
Error when trying to open books

### ISSUE THREAD

**Issue by mattdd50** [mkaflowski/ShelfTime#2]
I am able to login and see my list of audiobooks but when I click on one it just loads endlessly and the error message "Parameter specified as non-null is null: method kaf.audi..." shows on the screen.

![watch](https://github.com/user-attachments/assets/d5c61658-9df8-4e7a-9a77-3399fb47c2b3)

**Comment by mkaflowski** [comment]
Do you use Google Play version or APK?

**Comment by mkaflowski** [comment]
I have uploaded new version with Crashalitycs that could help me with localizing the problem but it will be on the Play Store in couple days.

- Does it happen for all books?
- The book that doesn't don't miss any important data like title, author etc?

**Comment by mattdd50** [comment]
I installed v1.8 and the same thing happened. It is happening with all books and it happens on both my admin account and other accounts. All the books have titles and authors. Let me know if there is anything specific you want me to try

**Comment by mkaflowski** [comment]
I dont see logs in Firebase :( Could you install this version?
https://we.tl/t-kHN1MakBSS
It should show whole message after error.

**Comment by mattdd50** [comment]
Long error message...

![Screenshot_20241018_225036_sysui.png](https://github.com/user-attachments/assets/854173b2-d881-4f4f-9f09-a21a30eabd9a)

![Screenshot_20241018_225053_sysui.png](https://github.com/user-attachments/assets/2ee95f69-c82b-46a4-ad7e-5b36de3c3f0e)

![Screenshot_20241018_225105_sysui.png](https://github.com/user-attachments/assets/cdb246c0-e59d-499a-a358-e6887e8c94ef)

![Screenshot_20241018_225120_sysui.png](https://github.com/user-attachments/assets/369597b4-d57f-498a-8c3d-5957ffc94b5c)

![Screenshot_20241018_225138_sysui.png](https://github.com/user-attachments/assets/e5cd9e37-8d22-4da2-becc-cb2582a89ee3)

![Screenshot_20241018_225150_sysui.png](https://github.com/user-attachments/assets/1bf6868c-f71c-4d26-9163-159e576b4dea)

![Screenshot_20241018_225158_sysui.png](https://github.com/user-attachments/assets/22df8bf1-9a7f-4205-b76c-4ae4c1888802)

![Screenshot_20241018_225206_sysui.png](https://github.com/user-attachments/assets/3d0da5e0-116b-42e1-9b34-cdf2a73344f8)

![Screenshot_20241018_225231_sysui.png](https://github.com/user-attachments/assets/e86e2dca-5399-49f3-a78e-385d3f31f6d5)

![Screenshot_20241018_225240_sysui.png](https://github.com/user-attachments/assets/0bf71b43-3834-48c6-b2ba-7da05bbdc64b)

![Screenshot_20241018_225247_sysui.png](https://github.com/user-attachments/assets/cc5010ff-cc36-4882-b476-0492a255d66f)

![Screenshot_20241018_225253_sysui.png](https://github.com/user-attachments/assets/d06d0e92-2b97-4cf3-826d-25986269dd96)

![Screenshot_20241018_225307_sysui.png](https://github.com/user-attachments/assets/996297d0-c592-4e38-b851-7320435281f5)

**Comment by mkaflowski** [comment]
Thank you. I think I have found the culprit (lack of user progress). Could you try v1.9?
The workaround could be playing some fragment of the book on phone or website to have some user progress in the server database.

**Comment by mattdd50** [comment]
v1.9 has fixed it. Your theory would definitely make sense because all of the books had never been played. Many thanks!

**Comment by mkaflowski** [comment]
Thank you for the help :)
