### ISSUE TITLE
Better offline support

### ISSUE THREAD

**Issue by darickc** [mkaflowski/ShelfTime#3]
Thank you for providing this app.  It works well for the most part.  I am able to download a book to my watch for offline listening, and it works while not at home.  But sometimes the app will close.  And then when I open the app, it wants to connect to the server. But if I am not at home, I am unable to connect since it is not exposed to the internet and I cannot view the list of books.  Even if they have been downloaded.

Would it be possible to display and select any downloaded books first, and then give the option to connect to the server?

Thank you.

**Comment by mkaflowski** [comment]
What version do you use? If there is no connection to the internet it should open in offline mode with books save in history.

**Comment by mkaflowski** [comment]
Current version is 1.9. 1.10 is on the way already uploaded. Could you check it?

**Comment by darickc** [comment]
I have 1.9 installed. It doesn't show that there is an update yet.  I'll try it out as soon as it is available.

**Comment by darickc** [comment]
I've install 1.10 and it seems to be much better.  The issue I have now is that after listening for a while (not sure how long, maybe 30 mins), it stops playing.  When I open up the app, it shows the paying controls (with the play/pause button), but there is no book, everything is just empty.  Kind of weird.  I have to swipe right to go back, then hit the continue button.  When it continues, it is a little behind where I was listening and I hit forward a few times.

**Comment by mkaflowski** [comment]
I have prepared v1.11 that has dedicated offline mode in login menu. If the bugs are still there could you provide me video of it? It is available in release tab and will be available on Google Play in couple days.
